
version: '3'
services:
  ewiz:
    container_name: ewiz
    image: richabrahams/custom_nginx 
    restart: unless-stopped
    networks:
      - webproxy
    environment:
      - VIRTUAL_HOST=www.eliquidwizard.com
      - LETSENCRYPT_HOST=www.eliquidwizard.com
      - LETSENCRYPT_EMAIL=richardabrahams75@gmail.com
    volumes:
      - ./build:/usr/share/nginx/html 
    networks:
      - webproxy

  #    docker run -d --name ewiz -e \
  #    "VIRTUAL_HOST=www.eliquidwizard.com" -e \
  #    "LETSENCRYPT_HOST=www.eliquidwizard.com" -e \
  #    "LETSENCRYPT_EMAIL=richardabrahams75@gmail.com" ewiz 
