version: '3'
services:
  ewiz:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    enviroment:
      - VIRTUAL_HOST=example.com,www.example.com,mail.example.com
      - LETSENCRYPT_HOST=example.com,www.example.com,mail.example.com
      - LETSENCRYPT_EMAIL=foo@bar.com
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/