version: '3'
services:
  ewiz:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    enviroment:
      - VIRTUAL_HOST=www.eliquidwizard.com
      - LETSENCRYPT_HOST=www.eliquidwizard.com
      - LETSENCRYPT_EMAIL=richardabrahams75@gmail.com
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/

     